name: WebApp Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: derickpimenta
        # Password or personal access token used to log against the Docker registry
        password: derick1991

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker build . --file WebApp.Dockerfile --tag derickpimenta/oai-embeddings:latest;

        docker build . --file BatchProcess.Dockerfile --tag derickpimenta/oai-batch:latest;
